// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxhoqxpvzthcvpznriiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4aG9xeHB2enRoY3Zwem5yaWl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjk0ODY3OTYsImV4cCI6MjA0NTA2Mjc5Nn0.imep9aBQD8uU_s3sdF_13qMzJpho7mBNsaOUFSp3QKg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);